
services:
  php:
    build: 
      context: .
    container_name: myshop_php-docker
    volumes:
      - "./src:/var/www/html"  # cartella sorgente
    ports:
     - 9090:80
    depends_on:
      - db
    networks:
      - app-network  

# Servizio MariaDB
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: myshop
      MYSQL_USER: root
      MYSQL_PASSWORD: Sandonaci94
      MYSQL_ROOT_PASSWORD: Sandonaci94
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql   # dati persistenti del database
    networks:
      - app-network
    user: "1000:1000"

# Volumi persistenti per i dati del database
volumes:
  db_data: 
    driver: local       # driver locale per il volume

 # Rete condivisa tra PHP e MariaDB
networks:
  app-network:
    driver: bridge   